### ISSUE TITLE
position

### ISSUE THREAD

**Issue by cy0707** [cy0707/about_css#1]
## 非背景的定位
1.  fixed----固定定位(position:fixed 默认是相对浏览器窗口定位的)，下面会有其相对于父元素定位的例子
2.  relative----相对定位（是决定定位的参考点）
3.  absolute----绝对定位（以相对定位为参考点）

#### relative---相对定位的理解（直接利用看到一篇博文的理解）
```html
<div id="first"> first</div>  
<div id="second">second</div> 
```
未使用相对定位
![position-03](https://cloud.githubusercontent.com/assets/15865210/16832470/eb0d67a0-49dc-11e6-8a22-b863f7a3774b.jpg)
使用相对定位之后
![position-04](https://cloud.githubusercontent.com/assets/15865210/16832479/f2382394-49dc-11e6-9c14-dbfba5c0179a.jpg)

总结：相对定位相对的是它原本在文档流中的位置而进行的偏移，而我们也知道relative定位也是遵循正常的文档流，它没有脱离文档流，但是它的top/left/right/bottom属性是生效的，可以说它是static到absoult的一个中间过渡属性，最重要的是它还占有文档空间，而且占据的文档空间不会随 top / right / left / bottom 等属性的偏移而发生变动，也就是说它后面的元素是依据虚线位置( top / left / right / bottom 等属性生效之前)进行的定位，这点一定要理解。

#### absolut---绝对定位的理解（absoulte是根据祖先类的border进行的定位）
例如：当我们有一个100*100大小的里面的盒子以300*300的外面的盒子为定位点，是用固定的数字进行定位的话。里面绝对定位的盒子，是以外面的那个相对定位的左上角（0,0）为坐标原点进行定位的
```css
.container {
	position: relative;
	width: 300px;
	height: 300px;
	margin: 100px auto;
	background-color: #96c18e;
}
.box {
	position: absolute;
	left: 100px;
	top: 100px;
	width: 100px;
	height: 100px;
	background-color: #567b68;
}
```
```html
<div class="container">
	<div class="box">我是定位盒子</div>
</div>
```
![position-01](https://cloud.githubusercontent.com/assets/15865210/16831823/a11b9bd8-49d9-11e6-89cb-60a90e27673a.png)

当我们对定位的单位改为百分比时。绝对定位的left,top取决于相对定位的宽度*百分比。：
```css
.box {
	position: absolute;
	left: 80%;
	top: 80%;
	width: 100px;
	height: 100px;
	background-color: #567b68;
}
```
![position-02](https://cloud.githubusercontent.com/assets/15865210/16832003/bbeb4868-49da-11e6-846a-aa8e5f38c4a2.png)

当我们想实现一个盒子垂直居中的话

```css
/*第一种方式*/
.box {
	position: absolute;
/*先取相对定位的盒子，50%，此时你会发现并没有居中，向左和下偏移了*/
	left:50%;
	top: 50%;
/*利用margin的负值，即绝对定位的宽度和高度的一般居中了*/
	margin-left: -50px;
	margin-top: -50px;
	width: 100px;
	height: 100px;
	background-color: #567b68;
}
```
其公式为：left:相对定位的宽度*50%,margin-left:负的固定定位的宽度*50%。top类似。

```css
/*第二种方式*/
.box {
	position: absolute;
/*把left,right,top,bottom都设置为0*/
	left:0;
	top:0;
	bottom: 0;
	right:0;
/*利用margin:auto*/
	margin: auto;
	width: 100px;
	height: 100px;
	background-color: #567b68;
}
```
对第二种方式的解释（来自博友）
通过以上描述，绝对居中（AbsoluteCentering）的工作机理可以阐述如下：
1.  在普通内容流（normal content flow）中，margin:auto的效果等同于margin-top:0;margin-bottom:0。
2.  position:absolute使绝对定位块跳出了内容流，内容流中的其余部分渲染时绝对定位部分不进行渲染。
3.  为块区域设置top: 0; left: 0; bottom: 0; right: 0;将给浏览器重新分配一个边界框，此时该块block将填充其父元素的所有可用空间，父元素一般为body或者声明为position:relative;的容器。
4.   给内容块设置一个高度height或宽度width，能够防止内容块占据所有的可用空间，促使浏览器根据新的边界框重新计算margin:auto
5.  由于内容块被绝对定位，脱离了正常的内容流，浏览器会给margin-top,margin-bottom相同的值，使元素块在先前定义的边界内居中。
简而言之（TL;DR）：绝对定位元素不在普通内容流中渲染，因此margin:auto可以使内容在通过top: 0; left: 0; bottom: 0;right: 0;设置的边界内垂直居中。

总结：absoulte定位，也称为绝对定位，虽然它的名字号曰“绝对”，但是它的功能却更接近于"相对"一词，为什么这么讲呢？原来，使用absoult定位的元素脱离文档流后，就只能根据祖先类元素(父类以上)进行定位，而这个祖先类还必须是以postion非static方式定位的， 举个例子，a元素使用absoulte定位，它会从父类开始找起，寻找以position非static方式定位的祖先类元素(注意，一定要是直系祖先才算哦~），直到<html>标签为止。
需要注意：relative和static方式在最外层时是以<body>标签为定位原点的，而absoulte方式在无父级是position非static定位时是以<html>作为原点定位。relative和static方式在最外层时是以<body>标签为定位原点的，而absoulte方式在无父级是position非static定位时是以<html>作为原点定位

#### left,right,top,bottom的理解

使用absoulte或fixed定位的话，必须指定 left、right、 top、 bottom 属性中的至少一个，否则left/right/top/bottom属性会使用它们的默认值 auto ，这将导致对象遵从正常的HTML布局规则，在前一个对象之后立即被呈递，简单讲就是都变成relative，会占用文档空间，这点非常重要，很多人使用absolute定位后发现没有脱离文档流就是这个原因少了left/right/top/bottom属性不行，那如果我们多设了呢？例如，我们同时设置了top和bottom的属性值，那元素又该往哪偏移好呢？
记住下面的规则：
 如果top和bottom一同存在的话，那么只有top生效。
 如果left和right一同存在的话，那么只有left生效。

#### fixed相对于父级容器的定位的理解
```css
.container {
	position: relative;
	float: right;
	width: 300px;
	height: 300px;
	margin: 100px auto;
	background-color: #96c18e;
}
/*fixed定位相对父级容器定位，不添加:top,bottom,left,right样式,通过margin定位*/
.box {
	width: 100px;
	height: 100px;
	background-color: #567b68;
}
```
```javascript
$(document).ready(function() {
	$(window).scroll(function(){
	 	var scrolltop = $(this).scrollTop();
		 if( scrolltop >= 100){
		 	$(".box ").css({
		 		position: "fixed",
		 		top: "120px"
		 	});;
		 }else{
		 	$(".container").css({
		 		position: "none",
		 		top: 0
		 });
	}
});
//这个就是网页中常用，滚动到一定距离的时候，菜单固定在左边或者右边的效果
```
## 背景定位(background-position)
其可能的值为以下：
1.  top left  top center  top right  center left  center center  center right  bottom left  bottom center
 bottom right
2.  具体的数字  例:20px 30px;
3.  百分比   例如:3% 4%
4.  如果您仅规定了一个关键词，那么第二个值将是"center"
5.  默认值：0% 0%

对于背景图片的定位，如果是数字的话就是相对于自身容器的左上角进行定位，向左或向下走具体的数字的像素距离，如果是百分比类似上面的非背景定位一样的其公式为：
#### 公式： (容器自身的宽度/高度 - 图片自身的宽度/高度) x 百分比

背景定位通常用做雪碧图（CSS雪碧图即CSS Sprites，也有人叫它CSS精灵，是一种CSS图像合并技术，该方法是将小图标和背景图像合并到一张图片上，然后利用CSS的背景定位来显示需要显示的图片部分。）

例如:默认状态是灰色的，当我们hover的是蓝色的，我们可以这两个状态合在一张图片上，当然实际运用中雪碧图有多张图，这里只小小示意一下
![position-08](https://cloud.githubusercontent.com/assets/15865210/16865703/713ec136-4a99-11e6-896c-eeae10db0af4.png)
```css
/*背景图的容器*/
.alogin-tabnav .icon {
    margin-right: 20px;
    display: inline-block;
    width: 20px;
    height: 22px;
    background-image: url(../images/alogin-item1.png);
    background-repeat: no-repeat;
/*背景图的初始定位*/
    background-position: left top;
    vertical-align: middle;
    transition: all 0.3s;
}
.alogin-tabnav .icon:hover{
/*背景图的定位改变了*/
    background-position: left bottom;
}
```
