### ISSUE TITLE
CSS3的calc()使用

### ISSUE THREAD

**Issue by cy0707** [cy0707/about_css#12]
## 前言

看了自适应图片的一些博文中，出现了这个所以想深入了解一些这个。
[博文](http://www.w3cplus.com/css3/how-to-use-css3-calc-function.html)

## 什么是calc()

calc是英文单词calculate(计算)的缩写，是css3的一个新增的功能，用来指定元素的长度。比如说，你可以使用calc()给元素的border、margin、pading、font-size和width等属性设置动态值。为何说是动态值呢?因为我们使用的表达式来得到的值。不过calc()最大的好处就是用在流体布局上，可以通过calc()计算得到元素的宽度。

## calc()能做什么

calc()能让你给元素的做计算，你可以给一个div元素，使用百分比、em、px和rem单位值计算出其宽度或者高度，比如说“width:calc(50% + 2em)”，这样一来你就不用考虑元素DIV的宽度值到底是多少，而把这个烦人的任务交由浏览器去计算。

## calc()语法

calc()语法非常简单，就像我们小时候学加 （+）、减（-）、乘（*）、除（/）一样，使用数学表达式来表示：

```css
.elm {
  width: calc(expression);
}
```
其中"expression"是一个表达式，用来计算长度的表达式。

## calc()的运算规则

* 使用“+”、“-”、“*” 和 “/”四则运算；
* 可以使用百分比、px、em、rem等单位；
* 可以混合使用各种单位进行计算；
* 表达式中有“+”和“-”时，其前后必须要有空格，如"widht: calc(12%+5em)"这种没有空格的写法是错误的；
* 表达式中有“*”和“/”时，其前后可以没有空格，但建议留有空格。

## 浏览器的兼容性

浏览器对calc()的兼容性还算不错，在IE9+、FF4.0+、Chrome19+、Safari6+都得到较好支持，同样需要在其前面加上各浏览器厂商的识别符，不过可惜的是，移动端的浏览器还没仅有“firefox for android 14.0”支持，其他的全军覆没。

在实际使用时，同样需要添加浏览器的前缀：

```css
 .elm {
	/*Firefox*/
	-moz-calc(expression);
	/*chrome safari*/
	-webkit-calc(expression);
	/*Standard */
	calc();
 }
```

## 例子

```html
  <h3>未使用cal()</h3>
    <div class="demo">
      <div class="box"></div>
    </div>
    <h3>使用cal()</h3>
    <div class="demo1">
      <div class="box"></div>
    </div>
```

```css
.demo, .demo1 {
        width: 300px;
        background-color: #60f;
        padding: 3px 0;
      }
      .box {
        width: 100%;
        background-color: #f60;
        height: 50px;
        padding: 10px;
        border: 5px solid green;
      }
      .demo1 .box {
        /*写给不支持calc()的浏览器的*/
        width: 90%;
        background-color: #f60;
        height: 50px;
        padding: 10px;
        border: 5px solid green;
        /*calc()*/
        width:-webkit-calc(100% - (10px + 5px) * 2);
        width:   -moz-calc(100% - (10px + 5px) * 2);
        width:    -ms-calc(100% - (10px + 5px) * 2);
        width:     -o-calc(100% - (10px + 5px) * 2);
        width:        calc(100% - (10px + 5px) * 2);
      }
```

结果如下所示

![calc](https://cloud.githubusercontent.com/assets/15865210/20470243/9c4562a6-afe1-11e6-94e2-3788f3c53ee2.png)
