### ISSUE TITLE
CSS中的简写

### ISSUE THREAD

**Issue by cy0707** [cy0707/about_css#14]
## 前言

最近在写font的简写的时候，浏览器总是说无效属性。看了好久才知道问题在哪里，平时都没有简写，所以这一块还是不太熟悉。所以想对这方面的知识进行一个总结，避免下次出错。

#### font -- 定义字体的属性

    取值:[ [ <font-style> || <font-variant> || <font-weight> ] <font-size> [ / <line-height> ] <font-family> ] 
    初始值: 根据字体其它属性的默认值
    继承性: 是
    适用于: 所有元素

例如：

```css
p{
    font:italic small-caps bold 12px/1.2em Arial;
}
```

注意：
 
* 字体连写至少要有font-size和font-family,否则表达式无效
* 字体大小必须写在字体的前面
* 多种字体之间用逗号隔开
* font各个属性之间用空格隔开

```css
/*这个是错误的写法，因为各个属性之间是空格隔开*/
font: 12px/1.6, 'Microsoft YaHei'; 
/*正确的写法*/
font: 12px/1.6  'Microsoft YaHei'; 
```
