### ISSUE TITLE
CSS3D动画的一些感悟

### ISSUE THREAD

**Issue by cy0707** [cy0707/about_css#20]
## 面向自己的是正向Z轴

**面向自己的是正向Z轴**这一点是很重要的，在3D的想象过程的，感觉很困难，总是没有较好的空间思维。总是忘记面向浏览器的我们，是从浏览器伸出来的Z轴。这一点很总要。不然你理解起来就会很困难。

## transform属性的中可以空格分来两个变形函数，是先执行前一个变形函数，在执行后一个变形函数，这两个变形函数是顺序的。

刚开始的时候，我以为，两个是没有顺序的，但是在看别人的css的时候，有的的地方，我想不通，如果那样写的话，不可能是那样的效果，最后我交换这两个变形函数，就出现我认为的效果，此时我才明白这个是有顺序的。

我们对下面那篇文章的分析一下，我出错的地方。

```html
<div class="container">
    <div class="piece-box">
        <div class="piece piece-1"></div>
        <div class="piece piece-2"></div>
        <div class="piece piece-3"></div>
        <div class="piece piece-4"></div>
        <div class="piece piece-5"></div>
        <div class="piece piece-6"></div>
    </div>
</div>
```

```css
/*容器*/
.container {
   -webkit-perspective: 1000px;
   -moz-perspective: 1000px;
   -ms-perspective: 1000px;
   perspective: 1000px;
}
/*piece盒子*/
.piece-box {
   position: relative;
   width: 200px;
   height: 200px;
   margin: 300px auto;
   perspective-origin: 50% 50%;
   -webkit-transform-style: preserve-3d;
   -moz-transform-style: preserve-3d;
   -ms-transform-style: preserve-3d;
   transform-style: preserve-3d;
}
/*piece通用样式*/
.piece {
   position: absolute;
   width: 200px;
   height: 200px;
   background: red;
   opacity: 0.5;

}
.piece-1 {
   background: red;
   -webkit-transform: rotateY(0deg) translateZ(173.2px);
   -ms-transform: rotateY(0deg) translateZ(173.2px);
   -o-transform: rotateY(0deg) translateZ(173.2px);
   transform: rotateY(0deg) translateZ(173.2px);

}
.piece-2 {
   background: #000;
   -webkit-transform: rotateY(60deg) translateZ(173.2px);
   -ms-transform: rotateY(60deg) translateZ(173.2px);
   -o-transform: rotateY(60deg) translateZ(173.2px);
   transform: rotateY(60deg) translateZ(173.2px);
}
.piece-3 {
   background: #006699;
   -webkit-transform: rotateY(120deg) translateZ(173.2px);
   -ms-transform: rotateY(120deg) translateZ(173.2px);
   -o-transform: rotateY(120deg) translateZ(173.2px);
   transform: rotateY(120deg) translateZ(173.2px);
}
.piece-4 {
   background: #009999;
   -webkit-transform: rotateY(180deg) translateZ(173.2px);
   -ms-transform: rotateY(180deg) translateZ(173.2px);
   -o-transform: rotateY(180deg) translateZ(173.2px);
   transform: rotateY(180deg) translateZ(173.2px);
}
.piece-5 {
   background: #FF0033;
   -webkit-transform: rotateY(240deg) translateZ(173.2px);
   -ms-transform: rotateY(240deg) translateZ(173.2px);
   -o-transform: rotateY(240deg) translateZ(173.2px);
   transform: rotateY(240deg) translateZ(173.2px);
}
.piece-6 {
   background: #FF6600;
   -webkit-transform: rotateY(300deg) translateZ(173.2px);
   -ms-transform: rotateY(300deg) translateZ(173.2px);
   -o-transform: rotateY(300deg) translateZ(173.2px);
   transform: rotateY(300deg) translateZ(173.2px);
}
```

* 如果每一个piece都没有使用变形属性的话，那么这六个正方形会重合在一起。

* 此时我们对第一个进行无旋转，**向正向Z轴走了173.2px.**

* 此时你可看见第一个正方形与后面五个有一点距离了。

* 我们再对第二个先进行沿着Y轴进行顺时针的60°。在向Z轴走了173.2px.

* 此时我们可以看见第二片和第一片进行无缝的结合在一起，并形成了一定的角度。有一点三维的感觉。
（如果此时我们先进行translateZ的话，再进行旋转的话，那么此时第一与第二就不在是无缝结合在一起，而是中心的重合在一起，两个正方形相交在一起了。）

* 所以第二片先在原地绕Y轴旋转60°。在向Z轴走了相同的距离。

其他的原理，具体可以参见下面的文章的链接。我只是总结我在看到这篇博文的我犯的错误与我的领悟。

## 参考文章

[带你玩转css3的3D！ ](http://bupt-hjm.github.io/2016/07/26/css-3d/)
[一款利用html5和css3实现的3D立方体旋转效果教程 ](http://www.jb51.net/css/454697.html)
