### ISSUE TITLE
Sass的学习笔记之二

### ISSUE THREAD

**Issue by cy0707** [cy0707/about_css#21]
## 不同样式风格的输出方法

* 嵌套输出方式-----nested
* 展开输出方式----- expanded  
* 紧凑输出方式-----compact 
* 压缩输出方式-----compressed

下面是一段sass代码，分别编译成以下四种格式的区别。

```sass
nav {
  ul {
    margin: 0;
    padding: 0;
    list-style: none;
  }

  li { display: inline-block; }

  a {
    display: block;
    padding: 6px 12px;
    text-decoration: none;
  }
}
```

#### 嵌套输出方式-----nested

在编译的时候带上参数“ --style nested”:
`sass --watch test.scss:test.css --style nested`

```css
nav ul {
  margin: 0;
  padding: 0;
  list-style: none; }
nav li {
  display: inline-block; }
nav a {
  display: block;
  padding: 6px 12px;
  text-decoration: none; }
```

#### 展开输出方式-----expanded

在编译的时候带上参数“ --style expanded”:
`sass --watch test.scss:test.css --style expanded

```css
nav ul {
  margin: 0;
  padding: 0;
  list-style: none;
}
nav li {
  display: inline-block;
}
nav a {
  display: block;
  padding: 6px 12px;
  text-decoration: none;
}
```

**注意：在结尾处的大括号是另在一行，不像嵌套编译的跟最后一行css在一行**

#### 紧凑输出方式-----compact 

在编译的时候带上参数“ --style compact ”:
`sass --watch test.scss:test.css --style compact `

```css
nav ul { margin: 0; padding: 0; list-style: none; }
nav li { display: inline-block; }
nav a { display: block; padding: 6px 12px; text-decoration: none; }
```

#### 压缩输出方式-----compressed

在编译的时候带上参数“ --style compressed”:
`sass --watch test.scss:test.css --style compressed`

压缩输出方式会去掉标准的 Sass 和 CSS 注释及空格。也就是压缩好的 CSS 代码样式风格：

```css
nav ul{margin:0;padding:0;list-style:none}nav li{display:inline-block}nav a{display:block;padding:6px 12px;text-decoration:none}
```

#### 声明变量

Sass变量包括是三个部分，分别如下：

* 声明变量的符号是`$`。
* 变量的名称
* 赋予变量的值

看一个例子

```sass
$brand-primary : darken(#428bca, 6.5%) ;
$btn-primary-color : #fff !default;
/**
  *$是变量的声明的符号
  * btn-primary-color和brand-primary是变量名
  * darken(#428bca, 6.5%)和#fff是变量的值
  * 如果值后面加上!default则表示默认值。
*/
```

#### 普通变量和默认变量

* 普通变量，在定义之后可以在全局范围内使用，例如上面的$brand-primary 。
* 默认变量，仅需要在值的后面加上!default即可，例如上面的$btn-primary-color。

sass 的默认变量一般是用来设置默认值，然后根据需求来覆盖的，覆盖的方式也很简单，只需要在默认变量后重新声明下变量即可。

#### 变量的调用

我们调用开始上面用Sass声明的两个变量

```Sass
.btn {
  color: $btn-primary-color;
}
```

编译出来的css

```css
.btn {
   color: #fff
}
```

#### 局部变量和全局变量

* 在选择器，函数，混合宏等等的外面定义的变量为全局变量。
* 当在局部范围（选择器内、函数内、混合宏内...）声明的变量称为局部变量。

```Sass
$color,: orange !default; //全局变量
.block {
    color: $color; //调用全局变量
}
.em {
    $color: red; //定义局部变量
     a {
          color: $color; //调用局部变量
      }
}
```

编译后的CSS为:

```css
.block {
    color: orange;
}
.em a {
    color: red;
}
```

当在局部范围（选择器内、函数内、混合宏内...）声明一个已经存在于全局范围内的变量时，局部变量就成为了全局变量的影子。基本上，局部变量只会在局部范围内覆盖全局变量。

#### 什么时候声明变量

创建变量只适用于感觉确有必要的情况下。不要为了某些骇客行为而声明新变量，这丝毫没有作用。只有满足所有下述标准时方可创建新变量：

* 该值至少重复出现了两次；
* 该值至少可能会被更新一次；
* 该值所有的表现都与变量有关（非巧合）。
* 基本上，没有理由声明一个永远不需要更新或者只在单一地方使用变量。

#### 引用父选择符：` &`

& 在编译时将被替换为父选择符，输出到 CSS 中。 也就是说，如果你有一个深层嵌套的规则，父选择符也会在 & 被替换之前被完整的解析。注意**父选择器在你写的选择器的前后的区别**

```Sass
#main {
  color: black;
  a {
    font-weight: bold;
    &:hover { color: red; }
  }
}
/*
  &:hover和 header&这个两个区别
  编译后的区别，一个在父级的后面和父级的前面
   #main a:hover和header #main a
*/
```

被编译为：

```css
#main {
  color: black; 
}
#main a {
    font-weight: bold; 
}
 #main a:hover {
      color: red;
 }
```

#### 嵌套

Sass 中还提供了选择器嵌套功能，但这也并不意味着你在 Sass 中的嵌套是无节制的，因为你嵌套的层级越深，编译出来的 CSS 代码的选择器层级将越深，这往往是大家不愿意看到的一点。这个特性现在正被众多开发者滥用。

Sass 的嵌套分为三种：

* 选择器嵌套
* 属性嵌套
* 伪类嵌套

选择器嵌套为样式表的作者提供了一个通过局部选择器相互嵌套实现全局选择的方法

```Sass
/*选择器嵌套*/
nav {
  a {
    color: red;
//父选择器& header是最高的层级
    header & {
      color:green;
    }
  }  
}
```

被编译后

```css
nav a {
   color: red;
}
header nav a {
   color: green;
}
```

Sass 中还提供属性嵌套，CSS 有一些属性前缀相同，只是后缀不一样，比如：border-top/border-right，与这个类似的还有 margin、padding、font 等属性。假设你的样式中用到了：

```Sass
//属性嵌套
.box {
//注意这个冒号，这是属性嵌套和选择器嵌套的最重要的区别
  border: {
   top: 1px solid red;
   bottom: 1px solid green;
  }
}
```

被编译成

.box {
    border-top: 1px solid red;
    border-bottom: 1px solid green;
}

其实伪类嵌套和属性嵌套非常类似，只不过他需要借助`&`符号一起配合使用。我们就拿经典的“clearfix”为例吧：

```Sass
.clearfix{
&:before,
&:after {
    content:"";
    display: table;
  }
&:after {
    clear:both;
    overflow: hidden;
  }
}
```

编译之后为

```css
clearfix:before, .clearfix:after {
  content: "";
  display: table;
}
.clearfix:after {
  clear: both;
  overflow: hidden;
}
```

#### 选择器嵌套的问题

* 选择器嵌套最大的问题是将使最终的代码难以阅读。开发者需要花费巨大精力计算不同缩进级别下的选择器具体的表现效果。

* 选择器越具体则声明语句越冗长，而且对最近选择器的引用(&)也越频繁。在某些时候，出现混淆选择器路径和探索下一级选择器的错误率很高，这非常不值得。

* 选择器的嵌套不宜过长，一般不超过三级，超过三级就需要考虑结构是否对不。
