### ISSUE TITLE
Sass的学习笔记之三

### ISSUE THREAD

**Issue by cy0707** [cy0707/about_css#22]
#### 声明混合宏

* 不带参数的混合宏，在Sass中，使用`@mixin`来声明一个混合宏

```Sass
@mixin border-radius {
    -webkit-border-radius: 5px;
    border-radius: 5px;
}
/*
其中 @mixin 是用来声明混合宏的关键词，有点类似 CSS 中的 @media、@font-face 一样。
border-radius 是混合宏的名称。
大括号里面是复用的样式代码。
*/
```

* 带参数的混合宏

```Sass
@mixin border-radius($radius:5px) {
    -webkit-border-radius: $radius;
    border-radius: $radius;
}
```

* 复杂的混合宏---你可以在大括号里面写上带有逻辑关系，帮助更好的做你想做的事情,如：

```Sass
@mixin box-shadow($shadow...) {
  @if length($shadow) >= 1 {
    @include prefixer(box-shadow, $shadow);
  } @else{
    $shadow:0 0 4px rgba(0,0,0,.3);
    @include prefixer(box-shadow, $shadow);
  }
}
```

这个 box-shadow 的混合宏，带有多个参数，这个时候可以使用“ … ”来替代。上面的意思是，当 $shadow 的参数数量值大于或等于“ 1 ”时，表示有多个阴影值，反之调用默认的参数值“ 0 0 4px rgba(0,0,0,.3) ”。

#### 调用混合宏

在 Sass 中通过 @mixin 关键词声明了一个混合宏，那么在实际调用中，其匹配了一个关键词“@include”来调用声明好的混合宏。例如在你的样式中定义了一个圆角的混合宏“border-radius”:

```Sass
@mixin border-radius{
    -webkit-border-radius: 3px;
    border-radius: 3px;
}
//调用

button {
    @include border-radius;
}
```

编译之后的CSS

```css
button {
  -webkit-border-radius: 3px;
  border-radius: 3px;
}
```

#### 传一个不带值的参数

```Sass
@mixin border-radius($radius){
  -webkit-border-radius: $radius;
  border-radius: $radius;
}
```

在混合宏`border-radius`中定义了一个不带任何值的参数的`$radius`,在调用的可以给这个混合宏传入参数值。

```Sass
.box {
    @include border-radius(3px);
}
```

被编译之后

```css
.box {
  -webkit-border-radius: 3px;
  border-radius: 3px;
}
```

#### 传入一个带值的参数

在Sass的混合宏中，还可以给混合宏的参数传入一个默认值，例如：

```Sass
@mixin border-radius($radius:3px) {
     -webkit-border-radius: $radius;
     border-radius: $radius;
}
```

在混合宏“border-radius”传了一个参数“$radius”，而且给这个参数赋予了一个默认值“3px”。

在调用类似这样的混合宏时，会多有一个机会，假设你的页面中的圆角很多地方都是“3px”的圆角，那么这个时候只需要调用默认的混合宏“border-radius”:

```Sass
.btn {
  @include border-radius;
}
```

被编译出来

```css
.btn {
  -webkit-border-radius: 3px;
  border-radius: 3px;
}
```

但有的时候，页面中有些元素的圆角值不一样，那么可以随机给混合宏传值，如：

```Sass
.box {
  @include border-radius(50%);
}
```

被编译出来的CSS

```css
.box {
  -webkit-border-radius: 50%;
  border-radius: 50%;
}
```

#### 传入多个参数

```Sass
@mixin center($width,$height){
  width: $width;
  height: $height;
  position: absolute;
  top: 50%;
  left: 50%;
  margin-top: -($height) / 2;
  margin-left: -($width) / 2;
}

//在混合宏`center`传入多个参数，在实际调用和其他混合宏是一样的。

.box-center {
    @include center(500px, 300px);
}
```

编译之后的CSS

```css
.box-center {
  width: 500px;
  height: 300px;
  position: absolute;
  top: 50%;
  left: 50%;
  margin-top: -150px;
  margin-left: -250px;
}
```

当混合宏传的参数过多之时，可以使用参数`...`来替代，例如：

```Sass
@mixin box-shadow($shadows...){
  @if length($shadows) >= 1 {
    -webkit-box-shadow: $shadows;
    box-shadow: $shadows;
  } @else {
    $shadows: 0 0 2px rgba(#000,.25);
    -webkit-box-shadow: $shadow;
    box-shadow: $shadow;
  }
}

//调用

.box {
  @include box-shadow(0 0 1px rgba(#000,.5),0 0 2px rgba(#000,.2));
}
``

编译出来的CSS

```css
.box {
  -webkit-box-shadow: 0 0 1px rgba(0, 0, 0, 0.5), 0 0 2px rgba(0, 0, 0, 0.2);
  box-shadow: 0 0 1px rgba(0, 0, 0, 0.5), 0 0 2px rgba(0, 0, 0, 0.2);
}
```

## 混合宏的不足

混合宏在实际编码中给我们带来很多方便之处，特别是对于复用重复代码块。但其最大的不足之处是会生成冗余的代码块。比如在不同的地方调用一个相同的混合宏时。如：

```Sass
@mixin border-radius{
  -webkit-border-radius: 3px;
  border-radius: 3px;
}

.box {
  @include border-radius;
  margin-bottom: 5px;
}

.btn {
  @include border-radius;
}
```

编译成的CSS

```css
.box {
  -webkit-border-radius: 3px;
  border-radius: 3px;
  margin-bottom: 5px;
}

.btn {
  -webkit-border-radius: 3px;
  border-radius: 3px;
}
/*.btn .box有相同的css,但是写了两遍*/
```

Sass 在调用相同的混合宏时，并不能智能的将相同的样式代码块合并在一起。这也是 Sass 的混合宏最不足之处。
