### ISSUE TITLE
Sass的学习笔记之四

### ISSUE THREAD

**Issue by cy0707** [cy0707/about_css#23]
## 继承

在 Sass 中继承，也是继承类中的样式代码块。在 Sass 中是通过关键词 “@extend”来继承已存在的类样式块，从而实现代码的继承。如下所示：

```Sass
.btn {
  border: 1px solid #ccc;
  padding: 6px 10px;
  font-size: 14px;
}

.btn-primary {
  background-color: #f36;
  color: #fff;
  @extend .btn;
}

.btn-second {
  background-color: orange;
  color: #fff;
  @extend .btn;
}
```

编译出来的CSS

```css
.btn, .btn-primary, .btn-second {
  border: 1px solid #ccc;
  padding: 6px 10px;
  font-size: 14px;
}

.btn-primary {
  background-color: #f36;
  color: #fff;
}

.btn-second {
  background-clor: orange;
  color: #fff;
}
```

从示例代码可以看出，在 Sass 中的继承，可以继承类样式块中所有样式代码，**而且编译出来的 CSS 会将选择器合并在一起，形成组合选择器**。

## 占位符%placeholder

Sass 中的占位符 %placeholder 功能是一个很强大，很实用的一个功能。他可以取代以前 CSS 中的基类造成的代码冗余的情形。因为 %placeholder 声明的代码，如果不被 @extend 调用的话，不会产生任何代码。

```Sass
%mt5 {
  margin-top: 5px;
}
%pt5{
  padding-top: 5px;
}
//调用

/*这段代码没有被 @extend 调用，他并没有产生任何代码块，
* 只是静静的躺在你的某个 SCSS 文件中。
* 只有通过 @extend 调用才会产生代码。
*/
.btn {
  @extend %mt5;
  @extend %pt5;
}

.block {
  @extend %mt5;

  span {
    @extend %pt5;
  }
}
```

编译后的CSS

```css
.btn, .block {
  margin-top: 5px;
}

.btn, .block span {
  padding-top: 5px;
}
```

从编译出来的 CSS 代码可以看出，通过 @extend 调用的占位符，编译出来的代码会将相同的代码合并在一起。这也是我们希望看到的效果，也让你的代码变得更为干净。

## 混合宏 VS 继承 VS 占位符的区别

什么时候用混合宏，什么时候用继承，什么时候使用占位符？

* Sass 中的混合宏使用

总结：编译出来的 CSS 清晰告诉了大家，他不会自动合并相同的样式代码，如果在样式文件中调用同一个混合宏，会产生多个对应的样式代码，造成代码的冗余，这也是 CSSer 无法忍受的一件事情。不过他并不是一无事处，他可以传参数。

建议：如果你的代码块中涉及到变量，建议使用混合宏来创建相同的代码块。

* Sass 中继承

总结：使用继承后，编译出来的 CSS 会将使用继承的代码块合并到一起，通过组合选择器的方式向大家展现，比如 .mt, .block, .block span, .header, .header span。这样编译出来的代码相对于混合宏来说要干净的多，也是 CSSer 期望看到。但是他不能传变量参数。

建议：如果你的代码块不需要专任何变量参数，而且有一个基类已在文件中存在，那么建议使用 Sass 的继承。

* 占位符

编译出来的 CSS 代码和使用继承基本上是相同，只是不会在代码中生成占位符 mt 的选择器。那么占位符和继承的主要区别的，**占位符是独立定义，不调用的时候是不会在 CSS 中产生任何代码；继承是首先有一个基类存在，不管调用与不调用，基类的样式都将会出现在编译出来的 CSS 代码中。

## 插值

使用 CSS 预处理器语言的一个主要原因是想使用 Sass 获得一个更好的结构体系。比如说你想写更干净的、高效的和面向对象的 CSS。Sass 中的插值(Interpolation)就是重要的一部分。让我们看一下下面的例子：

```Sass

//当你想设置属性值的时候，你可以使用字符串插入进来
$properties: (margin, padding);
@mixin set-value($side, $value) {
    @each $prop in $properties {
        #{$prop}-#{$side}: $value;
    }
}
.login-box {
    @include set-value(top, 14px);
}

//另一个有用的用法是构建一个选择器
@mixin generate-sizes($class, $small, $medium, $big) {
    .#{$class}-small { font-size: $small; }
    .#{$class}-medium { font-size: $medium; }
    .#{$class}-big { font-size: $big; }
}
@include generate-sizes("header-text", 12px, 20px, 40px);

//插值可以在@extend中使用

%updated-status {
    margin-top: 20px;
    background: #F00;
}
.selected-status {
    font-weight: bold;
}
$flag: "status";

.navigation {
    @extend %updated-#{$flag};
    @extend .selected-#{$flag};
}
```

编译的css

```css
.login-box {
    margin-top: 14px;
    padding-top: 14px;
}
.header-text-small { font-size: 12px; }
.header-text-medium { font-size: 20px; }
.header-text-big { font-size: 40px; }

.navigation {
    margin-top: 20px;
    background: #F00;
}
.selected-status, .navigation {
    font-weight: bold;
}
```

## 插值的限制

```Sass
$margin-big: 40px;
$margin-medium: 20px;
$margin-small: 12px;
@mixin set-value($size) {
//变量$margin没有找到
    margin-top: $margin-#{$size};
}
.login-box {
    @include set-value(big);
}
//上面这段代码会报错
//error style.scss (Line 5: Undefined variable: “$margin-".);

/*#{}语法并不是随处可用，你也不能在 mixin 中调用*/

@mixin updated-status {
    margin-top: 20px;
    background: #F00;
}
$flag: "status";

.navigation {
    @include updated-#{$flag};
}
//error style.scss (Line 7: Invalid CSS after "...nclude updated-": expected "}", was "#{$flag};")
```

## 注释

* 类似 CSS 的注释方式，使用 `/* `开头，结属使用 `*/ `
* 类似 JavaScript 的注释方式，使用`//`

两者区别，前者会在编译出来的 CSS 显示，后者在编译出来的 CSS 中不会显示，来看一个示例：

```Sass
//定义一个占位符

%mt5 {
  margin-top: 5px;
}

/*调用一个占位符*/

.box {
  @extend %mt5;
}
```

编译之后的css

```css
.box {
  margin-top: 5px;
}

/*调用一个占位符*/
```

## 数据类型

*  数字: 如，1、 2、 13、 10px；
*  字符串：有引号字符串或无引号字符串，如，"foo"、 'bar'、 baz；
*  颜色：如，blue、 #04a3f9、 rgba(255,0,0,0.5)；
*  布尔型：如，true、 false；
*  空值：如，null；
*  值列表：用空格或者逗号分开，如，1.5em 1em 0 2em 、 Helvetica, Arial, sans-serif。

#### 字符串

* 有引号字符串 (quoted strings)，如 "Lucida Grande" 、'http://sass-lang.com'；
* 无引号字符串 (unquoted strings)，如 sans-serifbold。

在编译 CSS 文件时不会改变其类型。只有一种情况例外，使用 #{ }插值语句 (interpolation) 时，有引号字符串将被编译为无引号字符串，这样方便了在混合指令 (mixin) 中引用选择器名。

```Sass
@mixin firefox-message($selector) {
  body.firefox #{$selector}:before {
    content: "Hi, Firefox users!";
  }
}
@include firefox-message(".header");
```

```css
body.firefox .header:before {
  content: "Hi, Firefox users!"; 
}
```

#### 值列表

所谓值列表 (lists) 是指 Sass 如何处理 CSS 中,像下面这样通过空格或者逗号分隔的一系列的值。

```css
.box {
    margin: 10px 15px 0 0;
}
```

**事实上，独立的值也被视为值列表——只包含一个值的值列表。**
