### ISSUE TITLE
Sass的学习笔记之五

### ISSUE THREAD

**Issue by cy0707** [cy0707/about_css#24]
## 运算

程序中的运算是常见的一件事情，但在 CSS 中能做运算的，到目前为止仅有 calc() 函数可行。但在 Sass 中，运算只是其基本特性之一。在 Sass 中可以做各种数学计算。

#### 加法和减法

加法运算是 Sass 中运算中的一种，在变量或属性中都可以做加法运算。Sass 的减法运算和加法运算类似。例如：

```Sass
//对于携带同类型的单位时。
.box1 {
  width: 20px + 8in;
}
//但对于携带不同类型的单位时，在 Sass 中计算会报错
.box2 {
  width: 20px + 1em;
}
//“Incompatible units: 'em' and ‘px'.”

$full-width: 960px;
$sidebar-width: 200px;

.content1 {
  width: $full-width -  $sidebar-width;
}

$full-width: 960px;

.content2 {
//同样的，运算时碰到不同类型的单位时，编译也会报错
  width: $full-width -  1em;
}
//Incompatible units: 'em' and ‘px’
```

编译后的css

```css
.box1 {
  width: 788px;
}
.content {
  width: 760px;
}
```

#### 乘法

乘法能够支持多种单位（比如 em ,px , %），但当一个单位同时声明两个值时会有问题。

```Sass
.box {
  width:10px * 2px;  
}
//20px*px isn't a valid CSS value.”

//如果进行乘法运算时，两个值单位相同时，只需要为一个数值提供单位即可。
//上面的示例可以修改成：
.box {
  width: 10px * 2;
}

// Sass 的乘法运算和加法、减法运算一样，在运算中有不同类型的单位时，也将会报错。
.box {
  width: 20px * 2em;
}
//“40em*px isn't a valid CSS value
```

编译后的css

```css
.box {
  width: 20px;
}
```

#### 除法

Sass 的乘法运算规则也适用于除法运算。不过除法运算还有一个特殊之处。众所周知“/”符号在 CSS 中已做为一种符号使用。因此在 Sass 中做除法运算时，直接使用“/”符号做为除号时，将不会生效，编译时既得不到我们需要的效果，也不会报错。一起先来看一个简单的示例：

```Sass
.box {
  width: 100px / 2;  
}
```

编译后的css

```css
.box {
  width: 100px / 2;
}
```

这样的结果对于大家来说没有任何意义。要修正这个问题，只需要给运算的外面添加一个小括号`( )`即可：

```Sass
.box {
  width: (100px / 2);  
}
```

编译出来的 CSS 如下：

```css
.box {
  width: 50px;
}
```

* 除了上面情况带有小括号，“/”符号会当作除法运算符之外，如果“/”符号在已有的数学表达式中时，也会被认作除法符号。

*  Sass 除法运算中，当用变量进行除法运算时，“/”符号也会自动被识别成除法，如下例所示：

```Sass
.box {
  width: 100px / 2 + 2in;  
}
$width: 1000px;
$nums: 10;

.item {
  width: $width / 10;  
}

.list {
  width: $width / $nums;
}
```

编译之后的css
```css
.box {
  width: 242px;
}
.item {
  width: 100px;
}

.list {
  width: 100px;
}
```

综合上述，`/`符号被当作除法运算符时有以下几种情况：

* 如果数值或它的任意部分是存储在一个变量中或是函数的返回值。
* 如果数值被圆括号包围。
* 如果数值是另一个数学表达式的一部分

Sass 的除法运算还有一个情况。我们先回忆一下，在乘法运算时，如果两个值带有相同单位时，做乘法运算时，出来的结果并不是我们需要的结果。但在除法运算时，如果两个值带有相同的单位值时，除法运算之后会得到一个不带单位的数值。如下所示：

```Sass
.box {
  width: (1000px / 100px);
}
```

```css
.box {
  width: 10;
}
```

## 变量的计算

在 Sass 中除了可以使用数值进行运算之外，还可以使用变量进行计算。在 Sass 中使用变量进行计算，这使得 Sass 的数学运算功能变得更加实用。一起来看一个简单的示例：

```Sass
$content-width: 720px;
$sidebar-width: 220px;
$gutter: 20px;

.container {
  width: $content-width + $sidebar-width + $gutter;
  margin: 0 auto;
}
```

编译之后的css

```css
.container {
  width: 960px;
  margin: 0 auto;
}
```

## 数字运算

在 Sass 运算中数字运算是较为常见的，数字运算包括前面介绍的：加法、减法、乘法和除法等运算。而且还可以通过括号来修改他们的运算先后顺序。和我们数学运算是一样的，一起来看个示例。

```Sass
.box {
  width: ((220px + 720px) - 11 * 20 ) / 12 ;  
}
```
编译后的css
```css
.box {
  width: 60px;
}
```

## 颜色运算

所有算数运算都支持颜色值，并且是分段运算的。也就是说，红、绿和蓝各颜色分段单独进行运算。如：

```Sass
p1 {
  color: #010203 + #040506;
}
//计算公式为 01 + 04 = 05、02 + 05 = 07 和 03 + 06 = 09， 并且被合成
p2 {
  color: #010203 * 2;
}
//计算公式为 01 * 2 = 02、02 * 2 = 04 和 03 * 2 = 06， 并且被合成为
```

编译之后的css

```css
p1 {
  color: #050709;
}
p2{
  color: #020406;
}
```

## 字符运算

在 Sass 中可以通过加法符号“+”来对字符串进行连接。

```Sass
$content: "Hello" + "" + "Sass!";
.box:before {
  content: " #{$content} ";
}
//除了在变量中做字符连接运算之外，还可以直接通过 +，把字符连接在一起：
div {
  cursor: e + -resize;
}
```

编译之后的css

```css
.box:before {
  content: " Hello Sass! ";
}
div {
  cursor: e-resize;
}
```

注意，如果有引号的字符串被添加了一个没有引号的字符串 （也就是，带引号的字符串在 + 符号左侧）， 结果会是一个有引号的字符串。 同样的，如果一个没有引号的字符串被添加了一个有引号的字符串 （没有引号的字符串在 + 符号左侧）， 结果将是一个没有引号的字符串。 例如：

```Sass
p:before {
  content: "Foo " + Bar;
  font-family: sans- + "serif";
}
```

编译之后的css

```css
p:before {
  content: "Foo Bar";
  font-family: sans-serif; 
}
```

**总结为：两个字符拼接，谁在前面，那么拼接之后的有无符号，就看前面的那个字符有无符号。**
