### ISSUE TITLE
Sass的学习笔记之六

### ISSUE THREAD

**Issue by cy0707** [cy0707/about_css#26]
#### `@if`

`@if` 指令是一个 SassScript，它可以根据条件来处理样式块，如果条件为 true 返回一个样式块，反之 false 返回另一个样式块。在 Sass 中除了` @if` 之，还可以配合 `@else if` 和 `@else` 一起使用。

假设要控制一个元素隐藏或显示，我们就可以定义一个混合宏，通过 `@if...@else... `来判断传进参数的值来控制 display 的值。如下所示：

```Sass
@mixin blockOrHidden($boolean: true) {
    @if $boolean {
           @debug '$boolean is #{$boolean}';
           display: block;
     }
   @else {
      @debug '$boolean is #{$boolean}';
       display: none;
    }
}

.block {
     @include blockOrHidden;
}

.hidden {
     @include blockOrHidden(false);
}
```

编译出来的css

```css
.block {
  display: block;
}

.hidden {
  display: none;
}
```

## `@for`循环

在 Sass 的 `@for`循环中有两种方式：

```Sass
@for $i from <start> through <end>
@for $i from <start> to <end>
```

* $i 表示变量
* start 表示起始值
* end 表示结束值

**这两个的区别是关键字 through 表示包括 end 这个数，而 to 则不包括 end 这个数。**

```Sass
@for $i from 1 through 3 {
  .item-#{$i} { width: 2em * $i; }
}
@for $i from 4 to 6 {
  .item-#{$i} { width: 2em * $i; }
}
```

编译出来的css
```css
//through 
.item-1 {
  width: 2em;
}
.item-2 {
  width: 4em;
}
.item-3 {
  width: 6em;
}

//to
.item-4 {
  width: 2em;
}
.item-5 {
  width: 4em;
}
```

例如生成网格系统的例子：

```Sass
$grid-prefix: span !default;
$grid-width: 60px !default;
$grid-gutter: 20px !default;

%grid {
  float: left;
  margin-left: $grid-gutter / 2;
  margin-right: $grid-gutter / 2;
}
@for $i from 1 through 12 {
  .#{$grid-prefix}#{$i}{
    width: $grid-width * $i + $grid-gutter * ($i - 1);
    @extend %grid;
  }  
}
```

编译出来的css
```css
.span1, .span2, .span3, .span4, .span5, .span6, .span7, .span8, .span9, .span10, .span11, .span12 {
  float: left;
  margin-left: 10px;
  margin-right: 10px;
}

.span1 {
  width: 60px;
}
/*2-11省略...*/
.span12 {
  width: 940px;
}
```

## `@while`

`@while` 指令也需要 SassScript 表达式（像其他指令一样），并且会生成不同的样式块，直到表达式值为 false 时停止循环。这个和 `@for` 指令很相似，只要 `@while` 后面的条件为 true 就会执行。

```Sass
$types: 4;
$type-width: 20px;

@while $types > 0 {
    .while-#{$types} {
        width: $type-width + $types;
    }
    $types: $types - 1;
}
```

编译出来的css

```css
.while-4 {
  width: 24px;
}
.while-3 {
  width: 23px;
}
.while-2 {
  width: 22px;
}
.while-1 {
  width: 21px;
}
```

## `@each`循环

`@each` 循环就是去遍历一个列表，然后从列表中取出对应的值。

`@each` 循环指令的形式：`@each $var in <list>`

在下面的例子中你可以看到，$var 就是一个变量名，`<list>` 是一个 SassScript 表达式，他将返回一个列表值。变量 $var 会在列表中做遍历，并且遍历出与 $var 对应的样式块。----类似与Javascript中的for...in循环。

```Sass
$list: adam john wynn mason kuroir;//$list 就是一个列表
@mixin author-images {
    @each $author in $list {
        .photo-#{$author} {
            background: url("/images/avatars/#{$author}.png") no-repeat;
        }
    }
}
.author-bio {
    @include author-images;
}
```

```css
author-bio .photo-adam {
  background: url("/images/avatars/adam.png") no-repeat; }
.author-bio .photo-john {
  background: url("/images/avatars/john.png") no-repeat; }
.author-bio .photo-wynn {
  background: url("/images/avatars/wynn.png") no-repeat; }
.author-bio .photo-mason {
  background: url("/images/avatars/mason.png") no-repeat; }
.author-bio .photo-kuroir {
  background: url("/images/avatars/kuroir.png") no-repeat; }
```

## 字符串函数

字符串函数顾名思意是用来处理字符串的函数。Sass 的字符串函数主要包括两个函数：

* unquote($string)：删除字符串中的引号
* quote($string)：给字符串添加引号。

####  unquote() 函数

unquote() 函数主要是用来删除一个字符串中的引号，如果这个字符串没有带有引号，将返回原始的字符串。简单的使用终端来测试这个函数的运行结果：

```Sass
.test1 {
    content:  unquote('Hello Sass!') ;
}
```
编译后的css

```css
.test1 {
  content: Hello Sass!;
 }
```

从测试的效果中可以看出，unquote( ) 函数只能删除字符串最前和最后的引号（双引号或单引号），而无法删除字符串中间的引号。如果字符没有带引号，返回的将是字符串本身。

####  quote()函数

quote() 函数刚好与 unquote() 函数功能相反，主要用来给字符串添加引号。如果字符串，自身带有引号会统一换成双引号 ""。如：

```Sass
.test1 {
    content:  quote('Hello Sass!');
}
```
编译后的css

```css
.test1 {
  content: "Hello Sass!";
}
```

使用 quote() 函数只能给字符串增加双引号，而且字符串中间有单引号或者空格时，需要用单引号或双引号括起，否则编译的时候将会报错。

同时 quote() 碰到特殊符号，比如： !、?、> 等，除中折号 - 和 下划线_ 都需要使用双引号括起，否则编译器在进行编译的时候同样会报错。

#### To-upper-case()、To-lower-case()

To-upper-case() 函数将字符串小写字母转换成大写字母。
To-lower-case() 函数 与 To-upper-case() 刚好相反，将字符串转换成小写字母。

```Sass
.test1 {
  text: to-upper-case(aaaaa);
  text: to-upper-case(aA-aAAA-aaa);
}
.test2 {
  text: to-lower-case(AAAAA);
  text: to-lower-case(aA-aAAA-aaa);
}
```

编译后的css

```css
.test1 {
  text: AAAAA;
  text: AA-AAAA-AAA;
}
.test2 {
  text: aaaaa;
  text: aa-aaaa-aaa;
}
```
