### ISSUE TITLE
mobile中footer与header

### ISSUE THREAD

**Issue by cy0707** [cy0707/about_css#3]
### 后退键与标题和右边一个功能键的布局（header不一直固定在顶部）

![header_01](https://cloud.githubusercontent.com/assets/15865210/14978257/1d4d69b8-114d-11e6-83b0-7dab23ff12c6.jpg)

```html
<div id="m_common_header">
    <header class="jd-header">
        <div class="jd-header-bar">
            <div class="jd-header-icon-back">
               <span></span>
             </div>        
            <div class="jd-header-title">京东全球购</div>
            <div class="jd-header-icon-shortcut ">
               <span></span>
            </div>   
         </div>    
         <ul class="jd-header-shortcut" style="display: none"></ul>
    </header>
</div>
```
```css
#m_common_header {
    z-index: 11;
    position: relative;
}
/*这个是移动端的公共头部，用了相对定位和层级为11，
 *不过是用id来写的样式，最好能用class来代替
*/
.jd-header {
    min-height: 44px;
    padding: 0;
    margin: 0;
    text-decoration: none;
    color: #252525;
    width: 100%;
}
/*头部设置了最小高度为44px,这里是iOS状态栏的高度，无论在iphone4,5,6,6
 *状态栏的高度是不发生变化的。所以高度是固定的值。统一规定字体的颜色。
*/
.jd-header, .jd-header a {
    font-family: "PingHei","Lucida Grande", "Lucida Sans Unicode", "STHeiti";
    color: #252525;
    text-decoration: none;
    font-size: 16px;
}
/*在这里，规定了统一的字体，字体大小，字体颜色，header跟在a标签一起写的做法
 *是因为a标签的字体只能在a标签里面写才生效，所以合在一起写,color和text-
decoration这两个属性重复了。
*/
.jd-header-bar {
    position: relative;
    background: #efefef url(../images/2015/header-bg.png?v=2) repeat-x 0 0;
    background-size: 100% 44px;
    min-height: 44px;
    border-bottom: 1px solid #bfbfbf;
    border-width: 0 0 1px 0;
}
/*对于headerbar的跟前面的m-commom-header类似，利用了sprite的图，平铺了背景，对于
 *border-bottom与border-width这两个同时写的做法，暂时还不太明白。记录一下。
*/
.jd-header-icon-back{
    position: absolute;
    width: 40px;
    height: 44px;
}
/*在返回按钮的图标外面套了一个div,直接写了，这个div的宽高，及点击区域大小
 *为40X44的区域，再以header-bar为基点，进行定位。
*/
.jd-header-icon-back span {
    width: 20px;
    height: 20px;
    background-position: -20px 0;
    margin: 12px 0 0 10px;
}
/*在这个返回区域的图标，直接写图标的大小，再以sprite图，定位出该图标
 *然后通过margin值，把图标调整到合适的位置。
*/
.jd-header-icon-back span, .jd-header-icon-shortcut span {
     display: block;
     background: url(../images/2015/jd-sprites.png?v=12) no-repeat;
     background-size: 200px 200px;
}
/*我们可以看见，京东的雪碧图是400X400，但是其background-size却是200X200
 *所以，这个图是两倍的图片,直接调用了2倍的图标。来进行是适配。
*/
.jd-header-title {
    margin: 0 50px;
    text-align: center;
    height: 44px;
    line-height: 44px;
    font-size: 16px;
}
/*这个是title，状态栏的标题，左右各50px,是为了左右两边的图标按钮的位置，文字的位置是居中
 *但是，这个是用div来写的，为了更好的语义化，建议用h2标签来写。
*/
.jd-header-icon-shortcut {
    position: absolute;
    right: 0;
    top: 0;
    width: 40px;
    height: 44px;
    overflow: hidden;
}
.jd-header-icon-shortcut span {
    width: 20px;
    height: 20px;
    background-position: -60px 0;
    margin: 12px 10px 0 10px;
}
.jd-header-icon-back span, .jd-header-icon-shortcut span {
    text-indent: -100px;
    overflow: hidden;
}
```
总结：这个格式的思路，外面一层为header，高度为44px，进行相对定位，左右两边的图标
包裹一层div做按钮的点击区域，事件控制（通过绝对定位放在所需的定位）。里面的span标签作为图标的。但是没有语意。用sprite图把所需的图标放在一块，通过背景图定位，把图标显示出来。对于一个返回键加标题类似的思路

### logo+搜索框+登录文字（固定在顶部）

![header_02](https://cloud.githubusercontent.com/assets/15865210/15006893/c1f91eee-1206-11e6-8392-b49427ccca6b.png)
![header_03](https://cloud.githubusercontent.com/assets/15865210/15040240/b37e1f4c-12e5-11e6-90c3-a1ad57699e5b.png)
点击前一个图的搜索框的时候，直接跳入第二张图，他们在一个页面，只不过刚开始隐藏起来的
对于这个有数据的录入，查询的，保存的时候，最好把他们放在一个页面，避免同过a标签进行页面跳转，这样不利于对数据进行保存和提取。
```html
	<!-- 最外的那层盒子，固定在顶部的，宽度是百分百的 -->
	<div id="fixedtop" class="showfixedtop" style="display: block;">
	<!-- 这个是显示出来的盒子，因为第一次未登录的时候，有一个banner下载盒子，那个在这个header的上面，默认情况是隐藏的 -->
		<div id="index_search_main"  class="jd-header-home-wrapper">
	<!-- 这个是整个导航条 -->
			<div class="jd-search-container on-blur" id="index_search_head">
	<!-- 这个是整个导航条的背景，滑动到一定距离的时候，背景颜色慢慢的变色 -->
				<div class="jd-search-box-cover" style="opacity: 0;"></div>
	<!-- 这是导航条里面的内容-->
				<div class="jd-search-box">
				<!-- 导航条内容的左右各margin：10px;-->
					<div class="jd-search-tb">
					<!-- 这个是京东logo以及一开始隐藏的小叉按钮， -->
						<div class="jd-search-icon">
						<!-- 京东logo -->
							<span class="jd-search-icon-logo">
								<i class="jd-sprite-icon"></i>
							</span>
							<!-- 另一个页面的小× -->
							<span id="index_search_bar_cancel" class="jd-search-icon-cancel">
								<i class="jd-sprite-icon"></i>
							</span>
						</div>
						<!-- 这是中间的输入框 -->
						<form id="index_searchForm" class="jd-search-form">
							<div class="jd-search-form-box">
							<!-- 这个是搜索的按钮，装饰物 -->
								<span class="jd-search-form-icon jd-sprite-icon"></span>
								<!-- 这个中input的输入文本框 -->
								<div class="jd-search-form-input">
									<input type="hidden" name="sid" value="31fac40d7b469d82dcac8db9ae4f5874">
									<input type="text" maxlength="20" autocomplete="off" id="index_newkeyword" name="keyword" value="" placeholder="100万件超级爆品疯抢！" class="hilight1">
									<input id="index_category" name="catelogyList" type="text" style="display:none;">
								</div>
								<!-- 另一个页面的关键字的，清楚小按钮 -->
								<a href="javascript:void(0);" class="jd-search-icon-close jd-sprite-icon"  id="index_clear_keyword"></a>
								<!-- 另一个页面的关键字的，搜索小按钮 -->
								<a href="javascript:void(0)" id="index_search_submit" class="jd-search-form-action">
									<span class="jd-sprite-icon"></span>
								</a>
							</div>
						</form>
						<!-- 这个是右边的登录入口 -->
						<div class="jd-search-login login-ing">
							<a id="index_searchLogin" href="#" class="J_ping" page_name="index" report-eventparam="" report-eventid="MHome_BLogin">
								<span class="jd-search-icon-login">登录</span>
							</a>
						</div>
					</div>
				</div>	       
			</div>
		</div>
	</div>
```

对于这个搜索页面，输入框获取焦点的话，弹出另一个页面的（其实开始是隐藏的div），进行更加详细的搜索，可以把位置相同的地方，放在一起，通过显示隐藏来呈现效果。
header的思路大部分就是上面两种，只不过header可能有3-4个功能按钮或者排版布局有些许的不同，
但是思路都差不多的。

## 一般布局浮动加，图标与文字在一张图上，点击图片进行页面跳转
![header_04](https://cloud.githubusercontent.com/assets/15865210/15062816/b7c42f4c-1376-11e6-8c9d-88355a11bb3b.png)

```html
<!-- 最外面的那一层，固定定位在最底层 -->
<div class="bottom-bar-pannel">
<!-- 这个是底部条的包含层 -->
    <div class="floor-container">
<!--四个按钮的那个盒子  -->
	<ul class="tab4">
<!-- 对于这个li用了左浮动，文字居中对齐，宽度为25%, 高度100%。 -->
	    <li>
<!-- 这个span设为inline-block，高度为100%，宽度为图片宽度，这个盒子在li里面是居中的 -->
		<span class="bar-img">
<!-- a标签是链接，进行跳转页面，里面的img的图标和文字是一张图，文字没有单独写 -->
		    <a class="J_ping" href="javascript:void(0)"><img src="..."></a>
		</span>
             </li>
	     <li>
		 <span class="bar-img">
		    <a class="J_ping"  href="http://m.jd.com/category/all.html"><img src="..."></a>
		 </span>
	     </li>
	     <li>
		 <span class="bar-img">
		    <a class="J_ping" href="http://p.m.jd.com/cart/cart.action"><img src="..."></a>
		  </span>
	    </li>
            <li>
		  <span class="bar-img">
		     <a class="J_ping" href="http://home.m.jd.com/myJd/home.action"><img src="..."></a>
		   </span>
	    </li>
       </ul>
    </div>
</div>
```
总结：这个是京东的布局，底部条用固定定位固定在底部，再把每一个按钮的外面的盒子，进行浮动，且宽度用百分比进行平分，再设置文字居中，对于里面的包含图片的盒子设为内联块元素，把图标与文字做成一张图，包含图片的那个盒子设置为图片的高度，还有图片的大小是用的两倍的。有固定宽高设置图片。

## 利用弹性布局，进行平分各个按钮的区域
```html
<!-- 固定在底部的盒子 -->
<div class="bottom-fxied" style="left: 0px; bottom: 0px; width: 100%; display: block;">
<!-- 对于footer区域，设置为块级标签，对其设置为弹性布局 display: flex;-webkit-box-pack: justify;
-webkit-box-align: center; 对块级中元素的子元素同时使用box-align和box-pack的居中属性：
box-align 实现垂直居中  box-pack 实现水平居中-->
	<footer>
	<!-- a标签使用flex:1,表明位置占一个 -->
		<a class="home">
		<!-- span使用是图标字体，为块级元素，p也是块级元素-->
			<span></span><p>首页</p>
		</a>
		<a class="delivery" data-href="https://h5.m.taobao.com/awp/mtb/olist.htm?sta=5">
			<span></span><p>物流</p>
		</a>
		<a class="cart" data-href="https://h5.m.taobao.com/awp/base/bag.htm?pds=cart%23h%23taojia">
			<span></span><p>购物车</p>
		</a>
		<a class="my" data-href="https://h5.m.taobao.com/awp/mtb/mtb.htm">
			<span></span><p>我的淘宝</p>
		</a>
		<a class="more" data-href="taobao://h5.m.taobao.com/moreapp/index.html?pds=apply%23h%23taojia">
			<span></span><p>更多</p>
		</a>
	</footer>
</div>
```
总结：利用弹性布局的，这个做结构更加简单。
