### ISSUE TITLE
compass学习笔记之三

### ISSUE THREAD

**Issue by cy0707** [cy0707/about_css#31]
## Utilities

Utilities都是mixin。分为以下几个模块。

* Color----颜色
* General----清除浮动
* Print----打印
* Sprites----雪碧图
* Tables-----表格

#### table

```sass
@import "compass/utilities/tables";
.example {
  table {
  	//外边框
    @include outer-table-borders(3px, #ccc);
    // 内边框
    @include inner-table-borders(1px, red);
//使单元格增加padding，是单元格之间不那么拥挤
    @include table-scaffolding();
//alternating-rows-and-columns($even-row-color, $odd-row-color, $dark-intersection, $header-color, //$footer-color) ---这五个参数分别为偶数行，奇数行，过渡值，footer,header的背景色。
    @include alternating-rows-and-columns(#974, #622, #717);
  }
}
```

## Sprites

**注意：该模块的只支持的图片格式是png格式**

* 在图片目录下，新建一个文件夹来放置需要合成的额图片
* 新建一个sass文件来合成图片，格式如下：

```sass
@import "compass/utilities/sprites";
//例如，所有图片在icons文件夹下，选择导入该文件下所有的png文件
@import "icons/*.png";
//中间的icons为文件夹的名字。调用该函数成长雪碧图的样式
@include all-icons-sprites();
```

编译后的css

```css
.icons-sprite, .icons-circle_01, .icons-circle_02, .icons-circle_03, 
.icons-circle_04, .icons-circle_05, .icons-circle_06 {
/*为自动合成的图*/
  background-image: url('/images/icons-s2299a69980.png');
  background-repeat: no-repeat;
}

.icons-circle_01 {
  background-position: 0 0;
}
.icons-circle_02 {
  background-position: 0 -90px;
}
.icons-circle_03 {
  background-position: 0 -180px;
}
.icons-circle_04 {
  background-position: 0 -270px;
}
.icons-circle_05 {
  background-position: 0 -360px;
}
.icons-circle_06 {
  background-position: 0 -450px;
}

```

* 当然，如果其他calss的也想引用这些图片可以这样做

`.box { @include all-icons-sprites(icons-circle_06); }`

* `$<map>-sprite-dimensions` ----其中map为文件夹的名，来表示是否输出的css是否包含图片的宽高。

* 对于active和hover时，可以在图片的名字加入-hover或者-active。通过配置后，也可以去掉中横线。
`$disable-magic-sprite-selectors`设置为true。

[具体配置参数](http://compass-style.org/help/tutorials/spriting/customization-options/)
