### ISSUE TITLE
替换元素与替换元素

### ISSUE THREAD

**Issue by cy0707** [cy0707/about_css#5]
## 替换元素以及非替换预算和行高的理解
感谢下面博文的分享。对我的很有帮助。读了下面的博文谈谈我的理解吧。

1）替换元素：替换元素是浏览器根据其标签的元素与属性来判断显示具体的内容。img、input、textarea、select、object 等都是替换元素，这些元素都没有实际的内容。在某些情况下audio、canvas 也是替换元素。css在某些情况下，在计算替换元素的margin或者auto属性值的时候，有些特别。一些替换元素，但并不是全部，有内在尺寸或者基线的元素，可以用vertical-align属性。
2）非替换元素：出掉替换元素，剩下的都是非替换元素。大多数元素是不可替换元素，他们将内容直接告诉浏览器，将其显示出来。比如 p的内容，浏览器将把这段内容直接显示出来。
3）行高、行距的概念：

![l_h_6](https://cloud.githubusercontent.com/assets/15865210/13808245/2cfce140-eba0-11e5-8fb7-07842dbac71c.png)

图中（来自博文）两条红线之间的距离就是行高（line-height），上一行的底线和下一行的顶线之间的距离就是行距，而同一行顶线和底线之间的距离是font-size的大小，行距的一半是半行距，半行距、font-size、line-height之间的关系就是：半行距 = （line-height - font-size）/2
4）4种合模型inline box、line box、content area、containing box 
*  inline box (行内框) 每个行内元素会生成一个行内框，行内框是一个浏览器渲染模型中的一个概念，无法显示出来，行内框的高度等于font-size，设定line-height时，行内框的高度不变，改变的是行距。
*  line box （行框） 行框是指本行的一个虚拟的矩形框，由该行中行内框组成。行框也是浏览器渲染模式中的一个概念，无法显示出来。行框高度等于本行中所有行内框高度的最大值。当有多行内容时，每一行都有自己的行框。
*  content area （内容区） 内容区是围绕着文字的一的一种盒子。
*  containing box containing box 是包裹着上述三种box的box，

其关系见下图：
![one](https://cloud.githubusercontent.com/assets/15865210/13808693/5e5ecfbc-eba2-11e5-965f-0a799ecea3f6.png)
![teo](https://cloud.githubusercontent.com/assets/15865210/13808696/5f1f31b2-eba2-11e5-8bc2-8d5c7e265513.png)
![three](https://cloud.githubusercontent.com/assets/15865210/13808695/5e607df8-eba2-11e5-88cc-45229ee46744.png)
![four](https://cloud.githubusercontent.com/assets/15865210/13808694/5e605f12-eba2-11e5-8809-65be293bfc5b.png)

5）行高的计算：
  *  对于块级元素，CSS属性line-height指定了元素内部line-boxes的最小高度。
  *  对于行内非替换元素，line-height用于计算line box的高度。
  *  对于行内替换元素，如button 或其他input元素，line-height没有影响（大多数浏览器并未有按照css的规范来）。
对上面的规则的解释：
*  对于块级元素
```html
<div>Lorem ipsum <span>hello</span>dolor sit amet </div>
<p>Lorem ipsum <span>hello</span>dolor sit amet </p>
```
```css
body {
  padding-top: 40px;
}
div {
  background-color: #7b9ab5;
}
p {
  padding: 20px;
  margin: 20px;
  line-height: 40px;
  background-color: #d9ab2b;
}
```
![l_h_1](https://cloud.githubusercontent.com/assets/15865210/13807958/ce44fd00-eb9e-11e5-9081-4f1106e96bee.png)

*  对于行内非替换元素与行内替换元素的计算比较
```html
<div>Lorem ipsum <span>hello</span>dolor sit amet </div>
<p>Lorem ipsum dolor <input type="text"> adipisicing elit. Ratione, laboriosam.</p>
<p>Lorem ipsum dolor <span>hello</span> adipisicing elit. Ratione, laboriosam.</p>
```
```css
body {
  padding-top: 40px;
}
div {
  background-color: #7b9ab5;
}
p {
  line-height: 40px;
  background-color: #d9ab2b;
}
span {
  padding: 40px;
  margin: 40px;
  background-color: #e8e6df;	
}
input {
  padding: 40px;
  margin: 40px;
  background-color: #e36a6c;
}
p span {
	line-height: 40px;
	padding: 0;
	margin: 0;
	background-color: #7b9ab5;
}
```
![l_h_4](https://cloud.githubusercontent.com/assets/15865210/13808051/2c9d31c4-eb9f-11e5-9603-eb2169d27ab1.png)

http://www.cnblogs.com/fengzheng126/archive/2012/05/18/2507632.html
https://segmentfault.com/a/1190000003038583
https://developer.mozilla.org/zh-CN/docs/Web/CSS/line-height
https://developer.mozilla.org/en-US/docs/Web/CSS/Replaced_element
