### ISSUE TITLE
常见的一些效果的做法

### ISSUE THREAD

**Issue by cy0707** [cy0707/about_css#7]
## 微信网页上input type="text"在苹果系统上不能输入内容

解决方法：

```css
-webkit-user-select: none;
```
或许你常常不希望用户在你的网站上选择文本,无论是否是出于版权的原因.通常大家会有js来实现,另一个方案就是,将-webkit-user-select 和-moz-user-select 的值设为none. 禁止用户进行复制和选择.

-ms-user-select 可设置 4 个值：
1. text – 可以选择文本
2. element – 可以选择文本，但选择范围受元素边界的约束
3. none – 不可以选择文本
4. auto – 如果该元素包含可编辑的文本（如输入元素或可编辑内容的元素），则可以选择文本。否则，元素内容是否可选择由父节点的值决定。

当然如果你确实需要这个-webkit-user-select这个属性，也可以这样写css代码（来源于上述的stackoverflow上的回答。

```css
*:not(input,textarea) {
    -webkit-touch-callout: none;
    -webkit-user-select: none;
}
```

## 模拟checkbox

```html
<div class="checkbtn">
     <input class="check" type="checkbox" checked="checked">
     <i class="icon-checked"></i>
</div>
```

```css
/*模拟checkbox*/
.checkbtn {
    position: relative;
    width: 1.24rem;
    height: 2.96rem;
}
.checkbtn input {
    position: absolute;
/*z-index的层级来提高，input来点击*/
    z-index: 10;
    width: 100%;
    height: 2.96rem;
/*注意这里是通过改变透明度，inputy隐藏起来*/
    opacity: 0; 
    cursor: pointer;  
}
.icon-checked {
    position: absolute;
    left: 0;
    right: 0;
    top: 0;
    bottom: 0;
    margin: auto;
    width: 0.6rem;
    height: 0.6rem;
    vertical-align:bottom;
    background-image: url(../images/no_checked.png);
    background-size: cover;
}
/*通过css选择器来改变check的图片*/
.check:checked+.icon-checked {
    background-image: url(../images/checked.png);
}
```

## 页面板块可横向滑动（在手机上，不会出现滚动条）

原理：原理就是利用overflow属性。设置其水平方向滚动，垂直方向hidden即可。

```css
.ul-list{
        padding:10px;
        padding-top:0;
        padding-bottom:20px;
        width:100%;
        box-sizing:border-box;
/*利用overflow属性*/
        overflow-x:scroll;
        overflow-y:hidden;
        white-space: nowrap;
        float:left;
｝
.ul-list li{
        position:relative;
        display:inline-block;
        margin-right:5px;
       vertical-align:middle;
 ｝
```
## 三角形

```css
.sanjiao {
    width: 0;
    height: 0;
    border-color: transparent transparent #fff;
    border-style: solid;
    border-width: 6px;
}
```

其原理是让元素的高宽为0，利用border来实现。你可以想象一下，border是每一条边都是三角形的。
四个边拼起来就是一个矩形。当你需要怎么的三角形的话，那么就把其他的边的颜色变成透明的颜色。
例如上面的就会画出一个尖角向上的三角形。

**需要理解border-width的长度指的是border三角形的高**

[有兴趣的可以看下这个问题](https://www.zhihu.com/question/35180018)，里面有详细的讨论。
